AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7 # keep in sync with lowest supported ruby version
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'test/integration/fakeapp/**/*'

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/FormatStringToken:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  EnforcedStyle: comparison

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: true # Opt-in

# Opt-in
Layout/FirstMethodArgumentLineBreak:
  Enabled: true # Opt-in

Layout/FirstMethodParameterLineBreak:
  Enabled: true # Opt-in

# https://github.com/rubocop-hq/rubocop/issues/5891
Style/SpecialGlobalVars:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RegexpLiteral:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Exclude:
  - test/fakegem/fakegem.gemspec
